/**
 * Génère `THIRD-PARTY-NOTICES.md` : la liste des composants tiers que les archives publiées
 * redistribuent réellement (runtime Node, shawl, dépendances npm du panel, de l'agent et du front),
 * plus les runtimes Java que l'agent télécharge à l'exécution.
 *
 * Le dépôt est MIT et public, et ses archives embarquent du code qui ne nous appartient pas :
 * cette liste est la contrepartie de cette redistribution. Elle se régénère (`pnpm release:notices`)
 * et la CI vérifie qu'elle est à jour (`--check`), sinon elle vieillit en silence.
 *
 * Portée assumée : la liste est l'arbre de dépendances de **production** de chaque paquet. Elle peut
 * être légèrement plus large que ce qu'une archive donnée embarque (un pair optionnel non installé,
 * par exemple) — sur-déclarer est sans conséquence, sous-déclarer serait le défaut à éviter.
 */
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { NODE_VERSION, SHAWL } from './constants.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

/** Les seuls paquets interrogeables : la commande passe par un shell, rien n'y est interpolé d'autre. */
const APPS = ['@mmo/panel', '@mmo/web', '@mmo/agent'];

/** `pnpm licenses list` d'un paquet du workspace → `{ licence: [nom, …] }`, trié. */
function licensesOf(filter) {
  if (!APPS.includes(filter)) throw new Error(`paquet inattendu : ${filter}`);
  // Commande en une chaîne, sans tableau d'arguments : sous Windows `pnpm` est un `.cmd`, que Node
  // refuse de lancer sans shell, et un tableau d'arguments AVEC shell est déprécié (DEP0190).
  const run = spawnSync(`pnpm --filter ${filter} licenses list --prod --json`, {
    cwd: ROOT,
    encoding: 'utf8',
    shell: true,
    maxBuffer: 32 * 1024 * 1024,
  });
  if (run.status !== 0 || !run.stdout.trim().startsWith('{')) {
    throw new Error(`pnpm licenses a échoué pour ${filter} : ${run.stderr || run.stdout}`);
  }
  const parsed = JSON.parse(run.stdout);
  const grouped = {};
  for (const [license, packages] of Object.entries(parsed)) {
    const names = packages
      .map((p) => p.name)
      // Les paquets du workspace sont notre propre code, sous licence du dépôt.
      .filter((name) => !name.startsWith('@mmo/') && !isPlatformBuild(name))
      .sort((a, b) => a.localeCompare(b));
    if (names.length > 0) grouped[license] = names;
  }
  return grouped;
}

/**
 * Les binaires **par plateforme** d'un paquet déjà listé (`@node-rs/argon2-linux-x64-gnu`,
 * `@esbuild/win32-x64`…) sont écartés : `pnpm licenses` ne voit que ceux installés sur l'hôte, donc
 * la liste changerait avec la machine qui la génère — et le contrôle en CI échouerait sur un autre
 * OS que celui du mainteneur (vécu : Windows dit `win32-x64-msvc`, le runner Linux dit
 * `linux-x64-gnu`). Ils sont couverts par l'entrée de leur paquet parent, sous la même licence.
 */
export function isPlatformBuild(name) {
  return /-(?:win32|linux|darwin|freebsd|android|openbsd|sunos)-(?:x64|arm64|ia32|arm|s390x|ppc64|riscv64|loong64|mips64el)(?:-(?:gnu|musl|msvc|eabi|eabihf))?$/.test(
    name,
  );
}

function section(title, note, grouped) {
  const lines = [`### ${title}`, '', note, ''];
  for (const license of Object.keys(grouped).sort((a, b) => a.localeCompare(b))) {
    lines.push(`**${license}** — ${grouped[license].join(', ')}`, '');
  }
  return lines.join('\n');
}

const header = `# Third-party notices

MinecraftManagerOnline is distributed under the MIT license (see [LICENSE](LICENSE)). The published
archives and the official Docker image also redistribute third-party components, listed here with
their own licenses. Each component remains under its own terms.

This file is generated by \`pnpm release:notices\` from the production dependency tree of each
package, plus the pinned binaries in \`tools/release/constants.mjs\`. Do not edit it by hand.
Per-platform native builds of a listed package (\`@node-rs/argon2-linux-x64-gnu\` and its siblings)
are covered by their parent entry, under the same license.

## Bundled in the archives

### Node.js runtime — ${NODE_VERSION}

Every panel and agent archive embeds an official Node.js build downloaded from
<https://nodejs.org/dist/v${NODE_VERSION}/>, verified against its \`SHASUMS256.txt\`. Node.js is
distributed under the MIT license and itself embeds components under other licenses (OpenSSL, ICU,
zlib, V8 and others): the complete notice ships inside the archive, in \`runtime/<version>/LICENSE\`.

### shawl — ${SHAWL.version} (Windows archives only)

The Windows service wrapper, downloaded from its official release and verified by hash. MIT license.
Its full legal notice is published by its author at <${SHAWL.legalUrl}>.
Project: <https://github.com/mtkennerly/shawl>.
`;

const body = [
  header,
  section(
    'Panel — npm dependencies',
    'Redistributed as installed packages inside `app/node_modules` of the panel archive.',
    licensesOf('@mmo/panel'),
  ),
  section(
    'Web interface — npm dependencies',
    'Compiled into the static bundle served by the panel (`web/`).',
    licensesOf('@mmo/web'),
  ),
  section(
    'Agent — npm dependencies',
    'Inlined by esbuild into the single-file agent bundle (`agent-<version>.js`).',
    licensesOf('@mmo/agent'),
  ),
  `## Downloaded at run time, not bundled

### Java runtimes

The agent installs a JRE by itself when a server needs one, from official sources, and the panel can
relay and cache those downloads for machines without direct Internet access:

- **Eclipse Temurin** (Adoptium) — GNU General Public License v2 with the Classpath Exception.
  <https://adoptium.net/docs/faq/>
- **Azul Zulu** — GNU General Public License v2 with the Classpath Exception, used as a fallback
  where Temurin publishes no build. <https://www.azul.com/products/core/>

These runtimes are never modified, and never redistributed inside our archives.

### Minecraft server software

MinecraftManagerOnline downloads no Minecraft server by itself in this version, and redistributes
none. Minecraft, Forge, NeoForge, Fabric, Velocity and Paper are the property of their respective
owners and remain governed by their own terms — including the Minecraft EULA, which the panel asks
you to accept explicitly, on your own behalf, before a server starts.
`,
].join('\n');

const target = path.join(ROOT, 'THIRD-PARTY-NOTICES.md');
if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8');
  if (current !== body) {
    console.error(
      'THIRD-PARTY-NOTICES.md est périmé : une dépendance a changé. Lancez `pnpm release:notices`.',
    );
    // Le diff, sinon le message ne dit pas CE qui a changé et il faut relancer localement pour le
    // savoir — or la CI est justement l'endroit où la différence apparaît (un autre OS, un autre
    // arbre installé).
    const avant = new Set(current.split('\n'));
    const apres = new Set(body.split('\n'));
    for (const ligne of apres)
      if (!avant.has(ligne) && ligne.trim() !== '') console.error(`  + ${ligne}`);
    for (const ligne of avant)
      if (!apres.has(ligne) && ligne.trim() !== '') console.error(`  - ${ligne}`);
    process.exit(1);
  }
  console.log('THIRD-PARTY-NOTICES.md est à jour.');
} else {
  writeFileSync(target, body);
  console.log(`THIRD-PARTY-NOTICES.md écrit (${String(body.length)} octets).`);
}
